# General setup
site_name: Appyx
site_url: https://bumble-tech.github.io/appyx/
site_author: Bumble
site_description: Model-driven navigation + UI components with gesture control for Compose Multiplatform

# Repository
repo_name: Appyx
repo_url: https://github.com/bumble-tech/appyx
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2022 - 2023 Bumble

# Navigation
docs_dir: documentation

nav:
  - Home: index.md
  - Using Appyx:
    - Quick start guide: how-to-use-appyx/quick-start.md
    - Codelabs: how-to-use-appyx/codelabs.md
    - Coding challenges: how-to-use-appyx/coding-challenges.md
    - Sample apps: how-to-use-appyx/sample-apps.md
  - Navigation:
    - Model-driven navigation: navigation/model-driven-navigation.md
    - NavModel:
      - Overview: navmodel/index.md
      - Back stack: navmodel/backstack.md
      - Spotlight: navmodel/spotlight.md
      - Cards: navmodel/cards.md
      - Tiles: navmodel/tiles.md
      - Promoter: navmodel/promoter.md
      - Writing your own: navmodel/custom.md
    - Composable navigation: navigation/composable-navigation.md
    - Implicit navigation: navigation/implicit-navigation.md
    - Explicit navigation: navigation/explicit-navigation.md
    - Deep linking: navigation/deep-linking.md
  - UI:
    - Children: ui/children-view.md
    - Transitions: ui/transitions.md
  - App:
    - Structuring your app navigation: apps/structure.md
    - Lifecycle: apps/lifecycle.md
    - Plugins: apps/plugins.md
    - ChildAware API: apps/childaware.md
    - Configuration changes: apps/configuration.md
    - Releases:
      - Downloads: releases/downloads.md
      - Changelog: releases/changelog.md
  - FAQ: faq.md
  - Appyx 2.x (experimental):
    - Home: 2.x/index.md
    - Appyx Navigation:
        - Overview: 2.x/navigation/index.md
        - Sample app: 2.x/navigation/sample-app.md
        - Quick start guide: 2.x/navigation/quick-start.md
        - Concepts:
          - Model-driven navigation: 2.x/navigation/concepts/model-driven-navigation.md
          - Composable navigation: 2.x/navigation/concepts/composable-navigation.md
          - Implicit navigation: 2.x/navigation/concepts/implicit-navigation.md
          - Explicit navigation: 2.x/navigation/concepts/explicit-navigation.md
        - Features:
          - Deep linking: 2.x/navigation/features/deep-linking.md
          - Scoped DI: 2.x/navigation/features/scoped-di.md
          - Lifecycle: 2.x/navigation/features/lifecycle.md
          - Material 3 support: 2.x/navigation/features/material3.md
          - Plugins: 2.x/navigation/features/plugins.md
          - ChildAware API: 2.x/navigation/features/childaware.md
          - Surviving configuration changes: 2.x/navigation/features/surviving-configuration-changes.md
        - Integrations:
          - Compose Navigation: 2.x/navigation/integrations/compose-navigation.md
          - DI frameworks: 2.x/navigation/integrations/di-frameworks.md
          - RIBs: 2.x/navigation/integrations/ribs.md
          - RxJava: 2.x/navigation/integrations/rx.md
          - ViewModel: 2.x/navigation/integrations/viewmodel.md
        - Multiplatform: 2.x/navigation/multiplatform.md
    - Appyx Interactions:
      - Overview: 2.x/interactions/index.md
      - Using components: 2.x/interactions/usage.md
      - Creating your own:
        - Component overview: 2.x/interactions/appyxcomponent.md
        - Transition model: 2.x/interactions/transitionmodel.md
        - Operations: 2.x/interactions/operations.md
        - UI representation: 2.x/interactions/ui-representation.md
        - KSP setup: 2.x/interactions/ksp.md
        - Gestures: 2.x/interactions/gestures.md
    - Appyx Components:
      - Overview: 2.x/components/index.md
      - Back stack: 2.x/components/backstack.md
      - Spotlight: 2.x/components/spotlight.md
      - Experimental: 2.x/components/experimental.md
    - Releases:
      - Downloads: 2.x/releases/downloads.md
      - Changelog: 2.x/releases/changelog.md
    - FAQ: 2.x/faq.md
    - Migration guide: 2.x/migrationguide.md


# theme configuration
theme:
  name: 'material'
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  language: en
  include_search_page: false
  search_index_only: true
  features:
#    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
  palette:
    scheme: default
    primary: amber
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.svg

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - include-markdown
  - macros:
      module_name: compose_mpp_sample
      on_error_fail: true
  - social:
      cards_layout_options:
        background_color: white
  - redirects:
      redirect_maps:
        'how-to-use-appyx/quick-start.md': '1.x/how-to-use-appyx/quick-start.md'
        'how-to-use-appyx/codelabs.md': '1.x/how-to-use-appyx/codelabs.md'
        'how-to-use-appyx/coding-challenges.md': '1.x/how-to-use-appyx/coding-challenges.md'
        'how-to-use-appyx/sample-apps.md': '1.x/how-to-use-appyx/sample-apps.md'
        'navigation/model-driven-navigation.md': 'navigation/concepts/model-driven-navigation.md'
        'navmodel/index.md': 'components/index.md'
        'navmodel/backstack.md': 'components/backstack.md'
        'navmodel/spotlight.md': 'components/spotlight.md'
        'navmodel/cards.md': 'components/experimental.md'
        'navmodel/tiles.md': '1.x/navmodel/tiles.md'
        'navmodel/promoter.md': '1.x/navmodel/promoter.md'
        'navmodel/custom.md': 'interactions/appyxcomponent.md'
        'navigation/composable-navigation.md': 'navigation/concepts/composable-navigation.md'
        'navigation/implicit-navigation.md': 'navigation/concepts/implicit-navigation.md'
        'navigation/explicit-navigation.md': 'navigation/concepts/explicit-navigation.md'
        'navigation/deep-linking.md': 'navigation/features/deep-linking.md'
        'ui/children-view.md': '1.x/ui/children-view.md'
        'ui/transitions.md': '1.x/ui/transitions.md'
        'apps/structure.md': 'navigation/concepts/composable-navigation.md'
        'apps/lifecycle.md': 'navigation/features/lifecycle.md'
        'apps/plugins.md': 'navigation/features/plugins.md'
        'apps/childaware.md': 'navigation/features/childaware.md'
        'apps/configuration.md': 'navigation/features/surviving-configuration-changes.md'
        'news.md': 'index.md'
        'interactions/uirepresentation.md': 'interactions/ui-representation.md'
        'navigation/navigation/composable-navigation.md': 'navigation/concepts/composable-navigation.md'
        'navigation/navigation/implicit-navigation.md': 'navigation/concepts/implicit-navigation.md'
        'navigation/navigation/explicit-navigation.md': 'navigation/concepts/explicit-navigation.md'
        'navigation/navigation/deep-linking.md': 'navigation/features/deep-linking.md'
        'navigation/apps/structure.md': 'navigation/concepts/composable-navigation.md'
        'navigation/apps/lifecycle.md': 'navigation/features/lifecycle.md'
        'navigation/apps/plugins.md': 'navigation/features/plugins.md'
        'navigation/apps/childaware.md': 'navigation/features/childaware.md'
        'navigation/apps/configuration.md': 'navigation/features/surviving-configuration-changes.md'
        'navigation/features/configuration.md': 'navigation/features/surviving-configuration-changes.md'

# extensions
markdown_extensions:
  - admonition
  - pymdownx.critic
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
