name: Post merge

on:
  push:
    branches:
      - 1.x
  workflow_dispatch:

jobs:
  build-sample-app:
    name: Build sample app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: gradle/wrapper-validation-action@v2
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true
      - name: Build
        run: ./gradlew :samples:app:assembleRelease
      - name: Upload sample app apk
        uses: actions/upload-artifact@v3
        with:
          name: sample-app
          path: samples/app/build/outputs/apk/release/app-release.apk
