name: Post merge

on:
  push:
    branches:
      - 1.x
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: sed -i 's/${POST_MERGE_RUN_ID}/${{ github.run_id }}/g' documentation/how-to-use-appyx/sample-apps.md
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force

  build-sample-app:
    name: Build sample app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: gradle/wrapper-validation-action@v2
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: true
      - name: Build
        run: ./gradlew :samples:app:assembleRelease
      - name: Upload sample app apk
        uses: actions/upload-artifact@v3
        with:
          name: sample-app
          path: samples/app/build/outputs/apk/release/app-release.apk
