name: Release

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: gradle/wrapper-validation-action@v2
      - uses: gradle/actions/setup-gradle@v3
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        with:
          cache-read-only: true
          arguments: |
            publishAppyxReleasePublicationToOSSRHRepository
            --no-parallel
            -Psigning.password=${{ secrets.SIGNING_PASSWORD }}
            -Psonatype.username=${{ secrets.SONATYPE_USERNAME }}
            -Psonatype.password=${{ secrets.SONATYPE_PASSWORD }}
